### ISSUE TITLE
Denmark Changes

### ISSUE THREAD

**Issue by AlexWyrmin** [Leviathonlx/MoreBookmarks-Plus#131]
I'm working on making Denmark more historically accurate and there are going to be changes to its de jure structure and history files. Can I propose for them to be made part of this mod once I'm done or should I just make my own sub-mod?

Just asking because I read that "#Don't want my de jure altered" in wap_de_jure_structure_effects.txt.

**Comment by Leviathonlx** [comment]
That note is me compatching BAP to not overwrite my map setup in 1066 and 867. Overall though I am typically very wary of changes to my history setup or character files since I do intentionally change things for the sake of gameplay in many areas as I fully agree with Paradox's 'gameplay before history' especially when sources for some areas are questionable anyway.  I'd suggest just showing me what you're changing and we can go from there.

**Comment by AlexWyrmin** [comment]
I fully intended to do so from the start, I just wanted to be sure I could post here what changes I'm going to make.

**Comment by AlexWyrmin** [comment]
While working on tweaking the de jure structure, I noticed the upper course of the Konge, the river on the border between the provinces of Ribe and Varde, had been traced wrong. Attached below are the corrections I made to the map.
![tree_leaf_01_mask](https://user-images.githubusercontent.com/83785222/188410267-9d4d77b3-8711-4f0b-9443-4e67219494eb.png)
[tree_leaf_high_generator_1.txt](https://github.com/Leviathonlx/MoreBookmarks-Plus/files/9488322/tree_leaf_high_generator_1.txt)
[tree_leaf_high_generator_2.txt](https://github.com/Leviathonlx/MoreBookmarks-Plus/files/9488325/tree_leaf_high_generator_2.txt)
[tree_leaf_high_generator_3.txt](https://github.com/Leviathonlx/MoreBookmarks-Plus/files/9488326/tree_leaf_high_generator_3.txt)
![provinces](https://user-images.githubusercontent.com/83785222/188410468-dbcc6fcf-6381-4497-9b9e-b36111675d51.png)
![rivers](https://user-images.githubusercontent.com/83785222/188410480-e95a1f32-d463-44a8-8676-d40c816ddb92.png)
